server:
  port: 3344

spring:
  application:
    name: cloud-config-server-center
  cloud:
    config:
      server:
        git:
          # git上面的仓库名字
          uri: https://github.com/wangzhs/cloud2020-config.git
          # 搜索目录 http://config-3344.com:3344/main/application-test2.yml
          search-paths:
#            - cloud2020-config
            - test
            - test2
      # 分支
      label: main
  # rabbitmq配置
  rabbitmq:
    host: txdev
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# rabbitmq相关配置，暴露bus监控断端点,刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"