server:
  port: 80

spring:
  application:
    name: cloud-alibaba-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"