server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route1
#          uri: http://localhost:8001
#          lb:// 表示基于服务注册中心负载均衡
          uri: lb://cloud-provider-hystrix-payment
          predicates:
            - Path=/payment/**
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 是否向服务中心注册自己
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负责均衡
    fetch-registry: true
    service-url:
      # 集群用,分隔开
      #设置与Eureka Service交互的地址 向那个服务注册
      defaultZone: http://eureka7001.com:7001/eureka