server:
  port: 7002


spring:
  application:
    name: cloud-eureka-service


eureka:
  instance:
    hostname: eureka7002.com
  client:
    # false表示不向服务中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，我的职责就是维护服务实列，并不需要检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Service交互的地址 查询和注册微服务都需要该地址
      defaultZone: http://eureka7001.com:7001/eureka
  server:
    # 关闭Eureka自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: false
    # 心跳监控时间
    eviction-interval-timer-in-ms: 2000