server:
  port: 9002

spring:
  application:
    name: cloud-alibaba-provider-paymeny
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        # 集群部署，nginx转发
        server-addr: 127.0.0.1:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"